TARGET=./src/version/build.go
CURRVERSION=$(sed -n 's/const BuildVersion = "\(.*\)/\1/p' < $TARGET) CURRVERSION="${CURRVERSION%\"}"
CURRVERSION=$((CURRVERSION + 1))

echo "Current version: ${CURRVERSION}"

cat > $TARGET <<EOF
package version

//BuildVersion is autogenerated
const BuildVersion = "${CURRVERSION}"
//BuildDate is autogenerated
const BuildDate = "$(date +"%Y-%m-%dT%H:%M:%S%z")"
EOF

APPNAME=$(basename "${PWD}")
echo "Building ${APPNAME}"
go build -o "${APPNAME}"

APPVERSION=$(./"${APPNAME}" -v 2>&1 | grep "${APPNAME}" | cut -f2 -d " ")
echo "Current version $APPVERSION"

ZIPNAME="${APPNAME}.${APPVERSION}.zip"
echo "Creating zipfile ${ZIPNAME}"
zip "${ZIPNAME}" "${APPNAME}"

echo "Done"
